= Make Alpine Linux VPS Image for Digital Ocean Droplets
:script-name: alpine-make-vm-image
:script-sha1: 33b338dc0d2ce67a8dd4f1701862f051aed565f1
:gh-name: alpinelinux/{script-name}
:version: 0.13.4

ifdef::env-github[]
image:https://github.com/{gh-name}/workflows/CI/badge.svg["Build Status", link="https://github.com/{gh-name}/actions"]
endif::env-github[]

This project provides a script for making customized https://alpinelinux.org/[Alpine Linux] VPS qcow2 images for Digital Ocean "Droplets" (their brand name for their VPS service instances). They are built for BIOS boot using https://syslinux.org/[Syslinux], x86_64, install `cloud-init`, `gcompat`, and otherwise only the bare minimum stuff needed.

This is a fork of the alpine-make-vm-image which has a different default branch for the DO image build and this different readme, but is otherwise the same as `

== Documentatiom for {script-name}

See the `main` branch for the documentstiom om the base image build script.

See the [docs](docs) directory and the [do-image](do-image) directory for information anout the DO-specific image in this branch.

== License

This project is licensed under http://opensource.org/licenses/MIT/[MIT License].
For the full text of the license, see the link:LICENSE[LICENSE] file.
